### PR TITLE
Add required by EC labels to the operator image

### PR DESCRIPTION
**Pull request by mmorhun**
This PR addresses [labels requirement]( https://enterprisecontract.dev/docs/ec-policies/release_policy.html#labels__required_labels) of RHTAP Enterprise Contract checks.

### CODE REVIEW

**Comment by mmorhun** [comment]
@chmeliik you may check EC documentation [here](https://enterprisecontract.dev/docs/user-guide/main/).
I just picked labels related failures from the pipeline and fixed.

**Comment by chmeliik** [comment]
> @chmeliik you may check EC documentation [here](https://enterprisecontract.dev/docs/user-guide/main/). I just picked labels related failures from the pipeline and fixed.

Where do you see the details for the EC failures? All I see is this, and the more details link just takes me to a generic landing page https://developers.redhat.com/products/trusted-software-supply-chain/overview

image

**Review by tkdchen — APPROVED** [review]

**Comment by chmeliik** [comment]
> @chmeliik you may check EC documentation [here](https://enterprisecontract.dev/docs/user-guide/main/).

Sound like this is the relevant rule: https://enterprisecontract.dev/docs/ec-policies/release_policy.html#labels__required_labels. Could you link it in the commit message?

**Review by rcerven — APPROVED** [review]

**Comment by chmeliik** [comment]
> > Where do you see the details for the EC failures?
> 
> For example in the corresponding task run logs or on the RHTAP dashboard.
> 
> > Could you link it in the commit message?
> 
> I am not a fun of long multiline commit messages. IMO, better have short clear commit message and full description in the PR.

Hmm, it's the opposite for me. I don't really care about the PR description, I always look for info in the commit messages. Especially when using `git log` / `git blame` locally to figure out why something was done the way it was.

**Comment by mkosiarc** [comment]
> > > Where do you see the details for the EC failures?
> > 
> > 
> > For example in the corresponding task run logs or on the RHTAP dashboard.
> > > Could you link it in the commit message?
> > 
> > 
> > I am not a fun of long multiline commit messages. IMO, better have short clear commit message and full description in the PR.
> 
> Hmm, it's the opposite for me. I don't really care about the PR description, I always look for info in the commit messages. Especially when using `git log` / `git blame` locally to figure out why something was done the way it was.

I agree with Adam, commit messages are way more important - that way you don't need to open the pull request to see what is going on - especially when looking up something that happened a long time ago.

**Comment by mmorhun** [comment]
@mkosiarc my commit message explains what's going on, doesn't it?

**Pull request merged**
